<img style="float: left;;" src='Figures/alinco.png' height="100"/></a>

# <center> <font color= #000047>  Librería NumPy</font> </center>




NumPy es una poderosa librería de álgebra lineal para Python. Lo que lo hace tan importante es que casi todas las librerías en el ecosistema de <a href='https://pydata.org/'>PyData</a> (pandas, scipy, scikit-learn, etc.) utilizan NumPy como uno de sus principales componentes básicos. 

NumPy también es increíblemente rápido, ya que tiene enlaces a bibliotecas C.

Aquí repasaremos los conceptos básicos de NumPy.

## Usando NumPy


In [1]:
import numpy as np


NumPy tiene muchas funciones y capacidades integradas. No veremos todos, nos centraremos en algunos de los aspectos más importantes de NumPy qué nos serán de utilidad en el curso como son: vectores, arreglos, matrices y generación de números aleatorios. 

# Arreglos en NumPy 

Los arreglos de NumPy son la principal forma en que utilizaremos esta librería a lo largo del curso. Los arreglos en NumPy se construyen de dos formas: vectores y matrices. Los vectores son matrices estrictamente unidimensionales (1D) y las matrices son elementos en 2D (pero se debe tener en cuenta que una matriz puede tener solo una fila o una columna) no son estrictamente cuadradas.

## Creando Arreglos en NumPy

### De una Lista de Python 

Podemos crear un arreglo directamente de una lista o listas de listas:



In [2]:
l1 = [1,2,3,4]
l1

[1, 2, 3, 4]

In [3]:
a = np.array(l1)
a

array([1, 2, 3, 4])

In [4]:
type(a)

numpy.ndarray

In [5]:
a.shape

(4,)

In [6]:
m1 = np.array([[[1,2,3],
          [2,3,4],
          [5,6,7]]])

In [7]:
m1.shape

(1, 3, 3)

## Métodos incorporados en NumPy

Hay muchas formas de como generar arreglos usando métodos incorporados.

### arange

Devuelve valores espaciados uniformemente dentro de un intervalo dado. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.arange.html)]

In [8]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### Creando arreglos de Ceros (zeros) y Unos (ones)

Podemos generar matrices de ceros ó unos. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)]

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### linspace 
Este método devuelve números espaciados uniformemente durante un intervalo especificado.[[referencia](https://www.numpy.org/devdocs/reference/generated/numpy.linspace.html)]

In [14]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [15]:
help(np.linspace)

Help on _ArrayFunctionDispatcher in module numpy:

linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None
)
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.16.0
        Non-scalar `start` and `stop` are now supported.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be obtained with ``np.linspace(start, stop, num).astype(int)``

    Parameters
    ----------
    start : array_like
        The starting value of the sequence.
    stop : array_like
        The end value of the sequence, unless `endpoint` is set to False.
        In that case, the sequence consists of all but the last of ``num + 1`

In [16]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [18]:
x = np.linspace(0,100)

In [19]:
# f(x) = x**2 + 3x
def f(x):
    return x**2 + 3*x

In [20]:
f(x)

array([0.00000000e+00, 1.02873803e+01, 2.89046231e+01, 5.58517284e+01,
       9.11286964e+01, 1.34735527e+02, 1.86672220e+02, 2.46938776e+02,
       3.15535194e+02, 3.92461474e+02, 4.77717618e+02, 5.71303623e+02,
       6.73219492e+02, 7.83465223e+02, 9.02040816e+02, 1.02894627e+03,
       1.16418159e+03, 1.30774677e+03, 1.45964182e+03, 1.61986672e+03,
       1.78842149e+03, 1.96530612e+03, 2.15052062e+03, 2.34406497e+03,
       2.54593919e+03, 2.75614327e+03, 2.97467722e+03, 3.20154102e+03,
       3.43673469e+03, 3.68025823e+03, 3.93211162e+03, 4.19229488e+03,
       4.46080800e+03, 4.73765098e+03, 5.02282382e+03, 5.31632653e+03,
       5.61815910e+03, 5.92832153e+03, 6.24681383e+03, 6.57363599e+03,
       6.90878800e+03, 7.25226989e+03, 7.60408163e+03, 7.96422324e+03,
       8.33269471e+03, 8.70949604e+03, 9.09462724e+03, 9.48808830e+03,
       9.88987922e+03, 1.03000000e+04])

In [21]:
#plot(x,f(x))

<font color=green>Note que `.linspace()` *incluye* el valor de paro. Para obtener un arreglo con fracciones comunes, hay que aumentar el numero de elementos:</font>

### eye

Mediante este método podemos crear la matriz identidad.[[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.eye.html)]

In [22]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random 
Numpy también tiene muchas formas de crear arreglos de números aleatorios:

### rand

Mediante este método podemos crear un arreglo de un tamaño dado con muestras aleatorias de una distribución uniforme en el intervalo ``[0, 1)``.[[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.rand.html)]

In [23]:
np.random.rand(100)

array([0.4452953 , 0.84174942, 0.57339131, 0.24171514, 0.41496303,
       0.33413038, 0.56459712, 0.60824888, 0.04891264, 0.80881474,
       0.42801533, 0.0492526 , 0.16713163, 0.02183464, 0.64501174,
       0.4669815 , 0.85645621, 0.60304165, 0.46484428, 0.30607061,
       0.72195716, 0.57439104, 0.13308902, 0.04305447, 0.39147097,
       0.37428413, 0.31422316, 0.10365021, 0.87574652, 0.74917481,
       0.75948728, 0.28455882, 0.71303473, 0.07985887, 0.87563884,
       0.86926095, 0.01435067, 0.93543813, 0.52215153, 0.54146265,
       0.18060951, 0.41472898, 0.45042932, 0.44568305, 0.51321893,
       0.90768652, 0.51300284, 0.46306934, 0.07052056, 0.88119249,
       0.50883249, 0.37073773, 0.80079434, 0.36068514, 0.93463194,
       0.89801085, 0.35411574, 0.90511398, 0.02027388, 0.43972198,
       0.95263964, 0.0943141 , 0.33705224, 0.41076423, 0.33056804,
       0.95291887, 0.98396613, 0.33404157, 0.7811257 , 0.99854839,
       0.44121319, 0.02133223, 0.97500594, 0.40573508, 0.26258

### randn

Este método devuelve una muestra (o muestras) de la distribución "normal estándar" [σ = 1] A diferencia de **rand**, que es uniforme, es más probable que aparezcan valores más cercanos a cero. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randn.html)]


In [24]:
np.random.rand(10)

array([0.5146852 , 0.50419259, 0.52289871, 0.64375615, 0.35787215,
       0.72257763, 0.8177009 , 0.32793324, 0.73572616, 0.07370255])

### randint
Devuelve números enteros aleatorios de un intervalo `mínimo` (inclusive) a `máximo` (exclusivo).  [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.randint.html)]

In [25]:
np.random.randint(1,100,10)

array([53, 98, 77, 17, 85, 76, 60, 88, 42, 97], dtype=int32)

### seed
Se puede utilizar para establecer el estado aleatorio, de modo que se puedan reproducir los mismos resultados "aleatorios". [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html)]

In [26]:
np.random.seed(5)

In [27]:
np.random.rand()

0.22199317108973948

In [28]:
np.random.seed(5)
np.random.rand()

0.22199317108973948

## Atributos y métodos de un Arreglo

Analicemos algunos atributos y métodos útiles para un arreglo:

In [29]:
arr = np.arange(25)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

## Reshape
Devuelve una matriz que contiene los mismos datos con una nueva forma. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.reshape.html)]

In [31]:
arr.shape

(25,)

In [32]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [34]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

### max, min, argmax, argmin

Estos son métodos útiles para encontrar valores máximos o mínimos. O para encontrar el índice donde tenemos valores máximos o mínimos:

In [35]:
arr.max(), arr.min()

(np.int64(24), np.int64(0))

In [36]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
arr.argmax()

np.int64(24)

In [38]:
arr.argmin()

np.int64(0)

## Shape

Shape es un atributo que tienen los arreglos (no un método): [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.shape.html)]

In [39]:
arr.shape

(25,)

### dtype

Podemos también obtener el tipo de datos del objeto en el arreglo. [[referencia](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.ndarray.dtype.html)]

In [40]:
arr.dtype

dtype('int64')

In [ ]:
type(arr)

In [41]:
l = [1, 'ss', help, [1,2]]
l

[1,
 'ss',
 Type help() for interactive help, or help(object) for help about object.,
 [1, 2]]