
<img style="float: left;;" src='Figures/alinco.png' height="100"/></a>

# <center> <font color= #000047>  Operaciones con NumPy</font> </center>



## Aritméticas

Podemos realizar fácilmente aritmeticas como *arreglo con arreglo* , o *escalar con arreglo*. Veamos algunos ejemplos: 

In [1]:
import numpy as np

In [2]:
l1 = [1, 1, 2, 3]
l2 = [2, 2, 3, 4]

In [3]:
print(l1 + l2)

[1, 1, 2, 3, 2, 2, 3, 4]


In [4]:
a1 = np.array(l1)
a2 = np.array(l2)

In [5]:
a1 + a2

array([3, 3, 5, 7])

In [6]:
2*a2 + 3*a1

array([ 7,  7, 12, 17])

In [7]:
a1.transpose()

array([1, 1, 2, 3])

In [8]:
a1@a2

np.int64(22)

In [ ]:
# Crear una matriz aleatoria de números enteros de dimensión 4x2 -> A
# Crear una matriz aleatoria de números enteros de dimensión 2x6 -> B
# Realizar la multiplicación de Matrices C = A*B
# Realizar la multiplicación de Matrices C = B*A



In [9]:
A = np.random.randint(100, size=(4,2))
A

array([[ 4, 45],
       [91, 21],
       [91, 61],
       [20, 70]], dtype=int32)

In [10]:
B = np.random.randint(100, size=(2,6))
B

array([[ 6, 93, 83, 54, 13, 99],
       [67, 27, 71, 62, 12, 84]], dtype=int32)

In [11]:
A.shape

(4, 2)

In [12]:
B.shape

(2, 6)

In [13]:
A@B

array([[ 3039,  1587,  3527,  3006,   592,  4176],
       [ 1953,  9030,  9044,  6216,  1435, 10773],
       [ 4633, 10110, 11884,  8696,  1915, 14133],
       [ 4810,  3750,  6630,  5420,  1100,  7860]], dtype=int32)

In [17]:
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 4 is different from 6)

In [18]:
np.dot(A,B)

array([[ 3039,  1587,  3527,  3006,   592,  4176],
       [ 1953,  9030,  9044,  6216,  1435, 10773],
       [ 4633, 10110, 11884,  8696,  1915, 14133],
       [ 4810,  3750,  6630,  5420,  1100,  7860]], dtype=int32)

In [19]:
np.dot(B,A)

ValueError: shapes (2,6) and (4,2) not aligned: 6 (dim 1) != 4 (dim 0)

## Funciones universales en los Arreglos

NumPy viene con muchass [funciones universales en los arreglos](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), or <em>ufuncs</em>, que son esencialmente operaciones matemáticas que se pueden aplicar al arreglo.<br>Veamos algunas funciones más comunes:

In [20]:
np.sqrt(a1)

array([1.        , 1.        , 1.41421356, 1.73205081])

In [21]:
np.exp(a1)

array([ 2.71828183,  2.71828183,  7.3890561 , 20.08553692])

In [22]:
np.sin(a1)

array([0.84147098, 0.84147098, 0.90929743, 0.14112001])

In [23]:
np.cos(a1)

array([ 0.54030231,  0.54030231, -0.41614684, -0.9899925 ])

In [24]:
np.log(a1)

array([0.        , 0.        , 0.69314718, 1.09861229])

In [25]:
np.min(a1)

np.int64(1)

In [26]:
np.max(a1)

np.int64(3)

## Resumen de Estadística sobre Arreglos

NumPy también ofrece métodos estadísticos como <em> sum </em>, <em> mean </em> y <em> max </em>. 

In [27]:
a1.sum()

np.int64(7)

In [28]:
a1.std()

np.float64(0.82915619758885)

In [29]:
a1.var()

np.float64(0.6875)

In [30]:
a1.mean()

np.float64(1.75)

In [31]:
A.sum()

np.int64(403)

## Lógica para el eje (axis)

Cuando trabajamos con arreglos bidimensionales, debemos considerar filas y columnas. En términos de un arreglo, el eje 0 (cero) es el eje horizontal (filas) y el eje 1 es el eje vertical (columnas). Los valores (0,1) corresponden al orden en el que método <tt> arr.shape </tt> da como salida.

Veamos cómo afecta esto a nuestros cálculos estadísticos resumidos de arriba.


In [32]:
A.shape

(4, 2)

Dando como entrada <tt>axis=0</tt>, estamos devolviendo la suma del arreglo a lo largo del eje vertical, esencialmente <tt>[(1+5+9), (2+6+10), (3+7+11), (4+8+12)]</tt>

<img src='Figures/axis_logic.png' width=400/>

In [33]:
A.sum(axis=0)

array([206, 197])

In [34]:
A.sum(axis=1)

array([ 49, 112, 152,  90])

Esto nos dice que <tt>arr_2d</tt> tiene 3 filas y 4 columnas.

En <tt>arr_2d.sum(axis=0)</tt>, se sumó el primer elemento de cada fila, luego el segundo elemento y así sucesivamente.

Entonces, ¿qué debería <tt>arr_2d.sum(axis=1)</tt> regresar?

## Ejercicio 1


### Numpy

1. Crear un vector con valores de 10 a 49.
2. Elevar al cuadrado a aquellos números divisibles por 3.
3. Redimensionar ese vector en una matriz de 20x2.
4. Crear una nueva matriz de 2x10 y multiplicarla a la matriz anterior.
5. Obtener la transpuesta de la matriz resultante.

In [35]:
#1.- Crear un vector con valores de 10 a 49
a = np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [36]:
#2.- Elevar al cuadrado a aquellos números divisibles por 3.

for i in range(len(a)):
    if a[i]%3==0:
        print(a[i]**2)

144
225
324
441
576
729
900
1089
1296
1521
1764
2025
2304


In [37]:
a[a%3==0]**2

array([ 144,  225,  324,  441,  576,  729,  900, 1089, 1296, 1521, 1764,
       2025, 2304])

In [38]:
#3.- Redimensionar ese vector en una matriz de 20x2.
a2 = np.arange(40)
a2.shape

(40,)

In [39]:
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [40]:
mat1 = a2.reshape(20,2)

In [41]:
#Crear una nueva matriz de 2x10 y multiplicarla a la matriz anterior.
mat2 = np.random.randint(100, size=(2,10))
mat2

array([[32, 88, 87, 84, 83, 34, 62, 86, 80, 68],
       [54, 91, 65, 42, 91, 39, 91, 74,  7, 65]], dtype=int32)

In [42]:
mat1@mat2

array([[  54,   91,   65,   42,   91,   39,   91,   74,    7,   65],
       [ 226,  449,  369,  294,  439,  185,  397,  394,  181,  331],
       [ 398,  807,  673,  546,  787,  331,  703,  714,  355,  597],
       [ 570, 1165,  977,  798, 1135,  477, 1009, 1034,  529,  863],
       [ 742, 1523, 1281, 1050, 1483,  623, 1315, 1354,  703, 1129],
       [ 914, 1881, 1585, 1302, 1831,  769, 1621, 1674,  877, 1395],
       [1086, 2239, 1889, 1554, 2179,  915, 1927, 1994, 1051, 1661],
       [1258, 2597, 2193, 1806, 2527, 1061, 2233, 2314, 1225, 1927],
       [1430, 2955, 2497, 2058, 2875, 1207, 2539, 2634, 1399, 2193],
       [1602, 3313, 2801, 2310, 3223, 1353, 2845, 2954, 1573, 2459],
       [1774, 3671, 3105, 2562, 3571, 1499, 3151, 3274, 1747, 2725],
       [1946, 4029, 3409, 2814, 3919, 1645, 3457, 3594, 1921, 2991],
       [2118, 4387, 3713, 3066, 4267, 1791, 3763, 3914, 2095, 3257],
       [2290, 4745, 4017, 3318, 4615, 1937, 4069, 4234, 2269, 3523],
       [2462, 5103, 4321, 3570, 49

In [43]:
mat1

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39]])

In [44]:
#Obtener la transpuesta de la matriz resultante.
mat1.transpose()

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30,
        32, 34, 36, 38],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31,
        33, 35, 37, 39]])

In [45]:
mat1.T

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30,
        32, 34, 36, 38],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31,
        33, 35, 37, 39]])

## Ejercicio 2

Se desea calcular el índice de masa corporal (IMC) de jugadores de un equipo de futbol. Los datos proporcionados corresponden a las listas de los nombres, altura y peso, tal como se muestra a continuación

In [ ]:
nombre= ['Bonifacio de Cifuentes',
'Ángel Machado Lara',
'Geraldo de Atienza',
'Onofre Posada Grande',
'Samu Cantón-Figuerola',
'Camilo Pol',
'Toni Galvez Lara',
'Lucho Manzano Rivas',
'Abraham Aroca',
'Anselmo Bartolomé Folch',
'Toni Inocencio Rozas Porras',
'Fausto Cortés-Arco',
'Baltasar Carreño Isern']

altura = [180, 215, 210, 210, 188, 176, 209, 200, 210, 188, 176, 209, 200]
peso = [69, 74, 72, 75, 68, 70, 71, 73, 69, 74, 72, 75, 68, 70, 71, 73]

El valor de IMC por cada jugador resulta de aplicar la fórmula:

$$IMC = \frac{peso(kg)}{altura(m)^2}$$

**Nota:** Los valores de altura están dados en centímetros por lo que deberá hacer laconversión a metros previo a la aplicación de la fórmula. Adicionalmente, una vez obtenido el IMC se solicita:

> a) Presentar el icm para cada jugador.

> b) Indicar en qué índice se encuentra el icm más alto y a qué jugador le pertenece.

> c) Calcular el promedio de los icm resultantes.

> d) Muestre los nombres de los jugadores en orden de su imc, desde el que tiene menorimc al que tiene mayor imc.