<img style="float: left;;" src='Figures/alinco.png' /></a>
    
# <center> <font color= #000047> Actividad 2: Espacios Vectoriales ( Ejercicios )</font>
___



## Espacios vectoriales

Un [espacio vectorial](https://es.wikipedia.org/wiki/Espacio_vectorial), $V$, sobre un <a href="https://es.wikipedia.org/wiki/Cuerpo_(matem%C3%A1ticas)">Campo</a>, $F$,  va a ser un [conjunto](http://relopezbriega.github.io/blog/2015/10/11/conjuntos-con-python/) en el que están definidas las operaciones de *<a href="https://es.wikipedia.org/wiki/Adici%C3%B3n_(matem%C3%A1ticas)">adición</a>* y  *multiplicación por <a href="http://es.wikipedia.org/wiki/Escalar_(matem%C3%A1tica)">escalares</a>*, tal que para cualquier par de elementos $x$ e $y$ en $V$, existe un elemento único $x + y$ en $V$, y para cada elemento $\alpha$ en $F$ y cada elemento $x$ en $V$, exista un único elemento $\alpha x$ en $V$, de manera que se cumplan las siguientes condiciones:

1. Para todo $x, y$ en $V$, $x + y = y + x$ ([conmutatividad](https://es.wikipedia.org/wiki/Conmutatividad) de la adición).

2. Para todo $x, y, z$ en $V$, $(x + y) + z = x + (y + z)$. (<a href="https://es.wikipedia.org/wiki/Asociatividad_(%C3%A1lgebra)">asociatividad</a> de la adición).

3. Existe un elemento en $V$ llamado $0$ tal que $x + 0 = x$ para todo $x$ en $V$.

4. Para cada elemento $x$ en $V$, existe un elemento $y$ en $V$ tal que $x + y = 0$.

5. Para cada elemento $x$ en $V$, $1 x = x$.

6. Para cada par, $\alpha, \beta$ en $F$ y cada elemento $x$ en $V$, $(\alpha \beta) x = \alpha (\beta x)$.

7. Para cada elemento $\alpha$ en $F$ y cada para de elementos $x, y$ en $V$, $\alpha(x + y) = \alpha x + \alpha y$.

8. Para cada par de elementos $\alpha, \beta$ en $F$ y cada elemento $x$ en $V$, $(\alpha +  \beta)x = \alpha x + \beta x$.

Los [espacios vectoriales](https://es.wikipedia.org/wiki/Espacio_vectorial) más comunes son $\mathbb{R}^2$, el cual representa el plano de 2 dimensiones y consiste de todos los pares ordenados de los [números reales](https://es.wikipedia.org/wiki/N%C3%BAmero_real):

$$\mathbb{R}^2 = \{(x, y): x, y \in \mathbb{R}\}$$

y $\mathbb{R}^3$, que representa el espacio ordinario de 3 dimensiones y consiste en todos los tríos ordenados de los  [números reales](https://es.wikipedia.org/wiki/N%C3%BAmero_real):

$$\mathbb{R}^3 = \{(x, y, z): x, y, z \in \mathbb{R}\}$$

Una de las grandes bellezas del [Álgebra lineal](http://relopezbriega.github.io/tag/algebra.html) es que podemos fácilmente pasar a trabajar sobre espacios de $n$ dimensiones, $\mathbb{R}^n$!

Tampoco tenemos porque quedarnos con solo los [números reales](https://es.wikipedia.org/wiki/N%C3%BAmero_real), ya que la definición que dimos de un [espacio vectorial](https://es.wikipedia.org/wiki/Espacio_vectorial) reside sobre un <a href="https://es.wikipedia.org/wiki/Cuerpo_(matem%C3%A1ticas)">Campo</a>; y los <a href="https://es.wikipedia.org/wiki/Cuerpo_(matem%C3%A1ticas)">campos</a> pueden estar representados por [números complejos](http://relopezbriega.github.io/blog/2015/10/12/numeros-complejos-con-python/). Por tanto también podemos tener [espacios vectoriales](https://es.wikipedia.org/wiki/Espacio_vectorial)  $\mathbb{C}^2, \mathbb{C}^3, \dots, \mathbb{C}^n$.

### Subespacios

Normalmente, en el estudio de cualquier estructura algebraica es interesante examinar subconjuntos que tengan la misma estructura que el [conjunto](http://relopezbriega.github.io/blog/2015/10/11/conjuntos-con-python/) que esta siendo considerado. Así, dentro de los [espacios vectoriales](https://es.wikipedia.org/wiki/Espacio_vectorial),  podemos tener [subespacios vectoriales](https://es.wikipedia.org/wiki/Subespacio_vectorial), los cuales son un subconjunto que cumplen con las mismas *propiedades* que el [espacio vectorial](https://es.wikipedia.org/wiki/Espacio_vectorial) que los contiene. De esta forma, $\mathbb{R}^3$ representa un [subespacio](https://es.wikipedia.org/wiki/Subespacio_vectorial) del [espacio vectorial](https://es.wikipedia.org/wiki/Espacio_vectorial) $\mathbb{R}^n$.



## Ejercicios:

<div class="alert alert-info"><strong>NOTA:</strong> 
Pueden adjuntar archivos word, jpg, pdf, etc.., para la solución de cada uno de los ejercicios</div>


**1.- Probar si el conjunto de matrices:**

$$\begin{Bmatrix} \begin{pmatrix}1 & \alpha\\ \beta & 1 \end{pmatrix} : \alpha, \beta \in \mathcal{R} \end{Bmatrix}$$

**es un espacio vectorial con su suma y producto usuales. Si no lo es, enunciar la serie de axiomas que no se satisfacen.**

In [1]:
import numpy as np

def pertenece_S(A):
    """Verifica si una matriz pertenece al conjunto S."""
    return (A[0,0] == 1) and (A[1,1] == 1)

# Ejemplos de matrices en S (nos sirve para ilustrar con claridad qué axiomas no se cumplen)
A = np.array([[1, 2], [3, 1]])   # α=2, β=3
B = np.array([[1, -1], [4, 1]])  # α=-1, β=4

print("=== Ejercicio 1: Conjunto de matrices S ===")
print("Matriz A:\n", A)
print("Matriz B:\n", B)

# Verificar cierre bajo suma
C = A + B
print("\nA + B =\n", C)
print("¿Pertenece A+B a S? ->", pertenece_S(C))

# Verificar cierre bajo multiplicación escalar
k = 3
kA = k * A
print(f"\n{k} * A =\n", kA)
print("¿Pertenece kA a S? ->", pertenece_S(kA))

# Verificar existencia de matriz cero
zero = np.zeros((2,2))
print("\nMatriz cero:\n", zero)
print("¿Pertenece la matriz cero a S? ->", pertenece_S(zero))

# Verificar inverso aditivo
negA = -A
print("\nInverso aditivo de A:\n", negA)
print("¿Pertenece -A a S? ->", pertenece_S(negA))


=== Ejercicio 1: Conjunto de matrices S ===
Matriz A:
 [[1 2]
 [3 1]]
Matriz B:
 [[ 1 -1]
 [ 4  1]]

A + B =
 [[2 1]
 [7 2]]
¿Pertenece A+B a S? -> False

3 * A =
 [[3 6]
 [9 3]]
¿Pertenece kA a S? -> False

Matriz cero:
 [[0. 0.]
 [0. 0.]]
¿Pertenece la matriz cero a S? -> False

Inverso aditivo de A:
 [[-1 -2]
 [-3 -1]]
¿Pertenece -A a S? -> False


**2.- Sea $V=\mathcal{R}^2$. Determinar si el conjunto:**

$$ H=\left\{(x,y): x^2+y^2 \leq 1 \right\}$$

**es un subespacio de V.**

In [2]:
def pertenece_H(v):
    """Verifica si un vector pertenece al conjunto H."""
    x, y = v
    return x**2 + y**2 <= 1

# Vectores de prueba
u = np.array([1,0])
v = np.array([0,1])

print("\n\n=== Ejercicio 2: Conjunto H en R^2 ===")
print("u =", u, " ¿u∈H? ->", pertenece_H(u))
print("v =", v, " ¿v∈H? ->", pertenece_H(v))

# Verificar cierre bajo suma
suma = u + v
print("\nu+v =", suma, " ¿u+v∈H? ->", pertenece_H(suma))

# Verificar cierre bajo multiplicación escalar
k = 2
ku = k*u
print(f"\n{k}*u =", ku, " ¿k*u∈H? ->", pertenece_H(ku))



=== Ejercicio 2: Conjunto H en R^2 ===
u = [1 0]  ¿u∈H? -> True
v = [0 1]  ¿v∈H? -> True

u+v = [1 1]  ¿u+v∈H? -> False

2*u = [2 0]  ¿k*u∈H? -> False


**3.- Sea que $P_n$ defina el conjunto de todos los polinomios de grado menor que $n$, se definen las operaciones de suma y multiplicación por un escalar como:**

$$( p  + q )( x ) = p ( x ) + q ( x )$$
$$( \alpha p )( x ) = \alpha p ( x )$$

**para todos los números reales x . Verificar si $P_n$ es un espacio vectorial.**

In [4]:
import numpy as np
import sympy as sp

x = sp.symbols('x')

# Definimos dos polinomios de grado < 3
p = x**2 + 2*x + 1
q = 3*x + 4

def pertenece_Pn(poly, n):
    """Verifica si el polinomio tiene grado < n"""
    return sp.degree(poly) < n

n = 3
print("=== Ejercicio 3: P_n (polinomios) ===")
print("Polinomio p(x):", p)
print("Polinomio q(x):", q)

# Cierre bajo suma
suma = p + q
print("\nSuma p+q =", suma, " -> ¿pertenece a P_n?", pertenece_Pn(suma, n))

# Cierre bajo multiplicación escalar
k = 5
escalar = k * p
print(f"\n{k}*p =", escalar, " -> ¿pertenece a P_n?", pertenece_Pn(escalar, n))

# Polinomio cero
cero = sp.Poly(0, x)
print("\nPolinomio cero:", cero, " -> ¿pertenece a P_n?", pertenece_Pn(cero, n))

# Inverso aditivo
inverso = -p
print("\nInverso aditivo de p:", inverso, " -> ¿pertenece a P_n?", pertenece_Pn(inverso, n))

=== Ejercicio 3: P_n (polinomios) ===
Polinomio p(x): x**2 + 2*x + 1
Polinomio q(x): 3*x + 4

Suma p+q = x**2 + 5*x + 5  -> ¿pertenece a P_n? True

5*p = 5*x**2 + 10*x + 5  -> ¿pertenece a P_n? True

Polinomio cero: Poly(0, x, domain='ZZ')  -> ¿pertenece a P_n? True

Inverso aditivo de p: -x**2 - 2*x - 1  -> ¿pertenece a P_n? True


**4.- Considere el conjunto $M_{2x2}$ de las matrices de $(2x2)$ y las operaciones convencionales de suma de matrices y producto de una matriz por un escalar. Verificar que este conjunto cumple con los 10 axiomas para ser un espacio vectorial.**

In [3]:
import numpy as np
import sympy as sp

A = np.array([[1, 2], [3, 4]])
B = np.array([[0, -1], [5, 2]])

print("\n\n=== Ejercicio 4: M_2x2 (matrices) ===")
print("Matriz A:\n", A)
print("Matriz B:\n", B)

# Cierre bajo suma
print("\nA + B =\n", A+B)

# Cierre bajo multiplicación escalar
k = -2
print(f"\n{k} * A =\n", k*A)

# Matriz cero
print("\nMatriz cero:\n", np.zeros((2,2)))

# Inverso aditivo
print("\nInverso aditivo de A:\n", -A)

print("\nConclusión: M_2x2 con operaciones usuales SÍ es un espacio vectorial.")



=== Ejercicio 4: M_2x2 (matrices) ===
Matriz A:
 [[1 2]
 [3 4]]
Matriz B:
 [[ 0 -1]
 [ 5  2]]

A + B =
 [[1 1]
 [8 6]]

-2 * A =
 [[-2 -4]
 [-6 -8]]

Matriz cero:
 [[0. 0.]
 [0. 0.]]

Inverso aditivo de A:
 [[-1 -2]
 [-3 -4]]

Conclusión: M_2x2 con operaciones usuales SÍ es un espacio vectorial.
