<img style="float: left;;" src='Figures/alinco.png' /></a>
    
# <center> <font color= #000047> Tarea 1: Eigenvectores y Eigenvalores</font>
___

Esta tarea consiste en calcular eigenvalores y eigenvectores de matrices siguiendo el calculo a mano, usando la librería numpy y sympy.

Los eigenvalores y eigenvectores son conceptos fundamentales en álgebra lineal y tienen aplicaciones en machine learning, física, ingeniería y más.

In [ ]:
import numpy as np

**1. Calcula los eigenvalores y eigenvectores de la siguiente matriz:**

$$A = \begin{bmatrix} 4 & 2 \\ 1 & 3 \end{bmatrix}$$

In [7]:
import numpy as np

A = np.array([[4, 2],
              [1, 3]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalores:")
print(eigenvalues)
print("\nEigenvectores (en columnas):")
print(eigenvectors)

Eigenvalores:
[5. 2.]

Eigenvectores (en columnas):
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


**2. Calcula los eigenvalores y eigenvectores de la siguiente matriz:**

$$B = \begin{bmatrix} 2 & 0 \\ 0 & 5 \end{bmatrix}$$

In [8]:
import numpy as np

B = np.array([[2, 0],
              [0, 5]])

eigenvalues, eigenvectors = np.linalg.eig(B)


print("Eigenvalores:")
print(eigenvalues)
print("\nEigenvectores (en columnas):")
print(eigenvectors)

Eigenvalores:
[2. 5.]

Eigenvectores (en columnas):
[[1. 0.]
 [0. 1.]]


**3. Eigenvalores y eigenvectores de una matriz 3x3**

Calcula los eigenvalores y eigenvectores de la siguiente matriz:

$$C = \begin{bmatrix} 1 & 2 & 3 \\ 0 & 4 & 5 \\ 0 & 0 & 6 \end{bmatrix}$$

In [9]:
import numpy as np

D = np.array([[0, 1],
              [-2, -3]])

eigenvalues, eigenvectors = np.linalg.eig(D)

print("Eigenvalores:")
print(eigenvalues)
print("\nEigenvectores (en columnas):")
print(eigenvectors)

Eigenvalores:
[-1. -2.]

Eigenvectores (en columnas):
[[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]


**4. Calcula los eigenvalores y eigenvectores de la siguiente matriz:**

$$D = \begin{bmatrix} 0 & 1 \\ -2 & -3 \end{bmatrix}$$

In [5]:
import sympy as sp
D = sp.Matrix([[0,1],[-2,-3]])
print("D =", D)
print("Eigenvaores and eigenvectores (sympy):")
print(D.eigenvects())

D = Matrix([[0, 1], [-2, -3]])
Eigenvaores and eigenvectores (sympy):
[(-2, 1, [Matrix([
[-1/2],
[   1]])]), (-1, 1, [Matrix([
[-1],
[ 1]])])]


**5. Crea una matriz cuadrada aleatoria de tamaño 4x4 y calcula sus eigenvalores y eigenvectores.**

In [4]:
import numpy as np
np.random.seed(42)
A_rand = np.random.randint(-5,6,size=(4,4)).astype(float)
w, v = np.linalg.eig(A_rand)
print("Random 4x4 matrix:\n", A_rand)
print("Eigenvalores (numpy):\n", w)
print("Eigenvectores (columns) (numpy):\n", v)

Random 4x4 matrix:
 [[ 1. -2.  5.  2.]
 [-1.  1.  4. -3.]
 [ 1.  5.  5.  2.]
 [-1. -2.  2.  2.]]
Eigenvalores (numpy):
 [-4.63082957+0.j          8.01456426+0.j          2.80813265+0.47383583j
  2.80813265-0.47383583j]
Eigenvectores (columns) (numpy):
 [[ 0.48730154+0.j          0.48436505+0.j         -0.92410583+0.j
  -0.92410583-0.j        ]
 [ 0.62582145+0.j          0.35688577+0.j          0.30313999+0.03956486j
   0.30313999-0.03956486j]
 [-0.4586953 +0.j          0.79607262+0.j         -0.1731891 -0.02808174j
  -0.1731891 +0.02808174j]
 [ 0.40060373+0.j          0.06550909+0.j         -0.09934022-0.10916802j
  -0.09934022+0.10916802j]]
